PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `Food` (`FoedevareNavn` TEXT, `FoodName` TEXT, `FoodID` INTEGER NOT NULL, `Taxonomi` TEXT, `FoodEx2Code` TEXT, `FoodGroupID` INTEGER, `FoedevareGruppe` TEXT, `FoodGroup` TEXT, PRIMARY KEY(`FoodID`));
INSERT INTO Food VALUES('hej','hejs',1,'he','er',3,'se','er');
INSERT INTO Food VALUES('hej','hejs',2,'he','er',3,'se','er');
INSERT INTO Food VALUES('hej','hejs',3,'he','er',3,'se','er');
INSERT INTO Food VALUES('hej','hejs',4,'he','er',3,'se','er');
INSERT INTO Food VALUES('hej','hejs',5,'he','er',3,'se','er');
INSERT INTO Food VALUES('hej','hejs',6,'he','er',3,'se','er');
COMMIT;